services:
  postgres:
    image: postgres:13.3
    environment:
      AUTH_DB_URL: jdbc:postgresql://localhost:5432/bodystat_auth
      BODYSTAT_DB_URL: jdbc:postgresql://localhost:5432/bodystat
      DB_USERNAME: postgres
      DB_PASSWORD: 142536

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile-eureka-server
    ports:
      - "8761:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-auth-service
    ports:
      - "0:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  calculation-service:
    build:
      context: .
      dockerfile: Dockerfile-calculation-service
    ports:
      - "0:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile-api-gateway
    ports:
      - "8765:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker