spring:
  application:
    name: CALCULATION-SERVICE

  datasource:
    url: ${BODYSTAT_DB_URL:jdbc:postgresql://localhost:5432/bodystat}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:142536}


  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

